import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

// read _category_.json
const exampleCategory = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'docs/example/_category_.json'), 'utf8')
);

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  draftSidebar: [{type: 'autogenerated', dirName: '.'}],
  exampleSidebar: [
    {
      type: 'category',
      label: exampleCategory.label,
      link: {
        type: 'generated-index',
        slug: '/example',
      },
      items: [{type: 'autogenerated', dirName: 'example'}],
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
